function mat1() {
  document.body.style.backgroundColor = "white";
  document.body.style.color = "black";
  btn.style.display = "block";
  btn1.style.display = "none";
}

let btn = document.getElementById("btn");
let btn1 = document.getElementById("btn1");

function mat() {
  document.body.style.backgroundColor = "black";
  document.body.style.color = "white";
  btn.style.display = "none";
  btn1.style.display = "block ";
}
